<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxcDoBw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxcDoBw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDxcDoBw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDxcDoBw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDxcDoBw\App_KernelDevDebugContainer([
    'container.build_hash' => 'DxcDoBw',
    'container.build_id' => 'ff99a08e',
    'container.build_time' => 1675326081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxcDoBw');
